function generate_plot(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Nov-2018 10:06:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',1.5,'Parent',axes1);
set(plot1(1),'DisplayName','gpu1');
set(plot1(2),'DisplayName','gpu2');
set(plot1(3),'DisplayName','gpu3');
set(plot1(4),'DisplayName','gpu4');

% Create ylabel
ylabel('Utilization (%)');

% Create xlabel
xlabel('Time (s)');

% Set the remaining axes properties
set(axes1,'FontSize',12,'XTick',[0 50 100 150 200],'XTickLabel',...
    ['0  ';'0.5';'1  ';'1.5';'2  ']);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12);

